metadata:
  id: 'SCF_DEP_AC18_STOP_TIMEOUT'
  name: "DEP-AC18: the service's task definition has a stopTimeout of at least 40 seconds"
  category: 'GENERAL_SECURITY'
definition:
  and:
    - cond_type: 'filter'
      attribute: 'resource_type'
      operator: 'within'
      value: ['aws_ecs_service']
    - cond_type: 'connection'
      resource_types: ['aws_ecs_service']
      connected_resource_types: ['aws_ecs_task_definition']
      operator: 'one_exists'
    - cond_type: 'attribute'
      resource_types: ['aws_ecs_task_definition']
      attribute: 'container_definitions'
      operator: 'regex_match'
      value: ".*'stopTimeout': ([4-9][0-9]|[1-9][0-9]{2,})[,}].*"
