metadata:
  id: 'SCF_DEP_AC23_ALARM_ALB_RESPONSE_TIME'
  name: 'DEP-AC23: the alarm ALB target response time p99 above 300 ms over 5 minutes exists'
  category: 'GENERAL_SECURITY'
definition:
  and:
    - cond_type: 'filter'
      attribute: 'resource_type'
      operator: 'within'
      value: ['aws_sns_topic']
    - cond_type: 'connection'
      resource_types: ['aws_sns_topic']
      connected_resource_types: ['aws_cloudwatch_metric_alarm']
      operator: 'one_exists'
    - cond_type: 'attribute'
      resource_types: ['aws_cloudwatch_metric_alarm']
      attribute: 'metric_name'
      operator: 'equals'
      value: 'TargetResponseTime'
    - cond_type: 'attribute'
      resource_types: ['aws_cloudwatch_metric_alarm']
      attribute: 'extended_statistic'
      operator: 'equals'
      value: 'p99'
    - cond_type: 'attribute'
      resource_types: ['aws_cloudwatch_metric_alarm']
      attribute: 'period'
      operator: 'equals'
      value: 300
    - cond_type: 'attribute'
      resource_types: ['aws_cloudwatch_metric_alarm']
      attribute: 'comparison_operator'
      operator: 'equals'
      value: 'GreaterThanThreshold'
    - cond_type: 'attribute'
      resource_types: ['aws_cloudwatch_metric_alarm']
      attribute: 'threshold'
      operator: 'equals'
      value: 0.3
